---
kind: pipeline                                        
type: macstadium
name: default

settings:
  image: MojaveWithXcode.img

steps:
- name: install
  commands:
  - pod --version
  - pod install

- name: test
  commands:
  - xcodebuild -version -sdk
  - X build test
